# Generated by Django 5.0.7 on 2024-07-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='deadline',
            field=models.DateField(),
        ),
    ]
