# Generated by Django 5.0.7 on 2024-08-15 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_entry_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(default='New entry', max_length=500),
        ),
        migrations.AlterField(
            model_name='entry',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
